//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Models
{
	// Mixin content Type 1120 with alias "contentModule"
	/// <summary>Content Module</summary>
	public partial interface IContentModule : IPublishedContent
	{
		/// <summary>Content</summary>
		IEnumerable<IPublishedContent> Content { get; }
	}

	/// <summary>Content Module</summary>
	[PublishedContentModel("contentModule")]
	public partial class ContentModule : PublishedContentModel, IContentModule
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contentModule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContentModule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContentModule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IEnumerable<IPublishedContent> Content
		{
			get { return GetContent(this); }
		}

		/// <summary>Static getter for Content</summary>
		public static IEnumerable<IPublishedContent> GetContent(IContentModule that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("content"); }
	}
}
