//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Models
{
	// Mixin content Type 1107 with alias "navigationFooter"
	/// <summary>_Navigation Footer</summary>
	public partial interface INavigationFooter : IPublishedContent
	{
		/// <summary>Footer</summary>
		IEnumerable<IPublishedContent> NavigationListFooter { get; }
	}

	/// <summary>_Navigation Footer</summary>
	[PublishedContentModel("navigationFooter")]
	public partial class NavigationFooter : PublishedContentModel, INavigationFooter
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigationFooter";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationFooter(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationFooter, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("navigationListFooter")]
		public IEnumerable<IPublishedContent> NavigationListFooter
		{
			get { return GetNavigationListFooter(this); }
		}

		/// <summary>Static getter for Footer</summary>
		public static IEnumerable<IPublishedContent> GetNavigationListFooter(INavigationFooter that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("navigationListFooter"); }
	}
}
