//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Models
{
	// Mixin content Type 1109 with alias "navigationFooterUtility"
	/// <summary>_Navigation Footer Utility</summary>
	public partial interface INavigationFooterUtility : IPublishedContent
	{
		/// <summary>Footer Utility</summary>
		IEnumerable<IPublishedContent> NavigationListFooterUtility { get; }
	}

	/// <summary>_Navigation Footer Utility</summary>
	[PublishedContentModel("navigationFooterUtility")]
	public partial class NavigationFooterUtility : PublishedContentModel, INavigationFooterUtility
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigationFooterUtility";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationFooterUtility(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationFooterUtility, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Utility
		///</summary>
		[ImplementPropertyType("navigationListFooterUtility")]
		public IEnumerable<IPublishedContent> NavigationListFooterUtility
		{
			get { return GetNavigationListFooterUtility(this); }
		}

		/// <summary>Static getter for Footer Utility</summary>
		public static IEnumerable<IPublishedContent> GetNavigationListFooterUtility(INavigationFooterUtility that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("navigationListFooterUtility"); }
	}
}
