//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Models
{
	/// <summary>Site Config</summary>
	[PublishedContentModel("siteConfig")]
	public partial class SiteConfig : PublishedContentModel, IBusinessAddress, IBusinessTimingsNested, IImageFavicon, IImageLogo, INavigationFooter, INavigationFooterUtility, INavigationHeader, INavigationHeaderUtility
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "siteConfig";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SiteConfig(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SiteConfig, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address 1
		///</summary>
		[ImplementPropertyType("businessAddress1")]
		public string BusinessAddress1
		{
			get { return MBran.Models.BusinessAddress.GetBusinessAddress1(this); }
		}

		///<summary>
		/// Address 2
		///</summary>
		[ImplementPropertyType("businessAddress2")]
		public string BusinessAddress2
		{
			get { return MBran.Models.BusinessAddress.GetBusinessAddress2(this); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("businessAddressCity")]
		public string BusinessAddressCity
		{
			get { return MBran.Models.BusinessAddress.GetBusinessAddressCity(this); }
		}

		///<summary>
		/// Country
		///</summary>
		[ImplementPropertyType("businessAddressCountry")]
		public object BusinessAddressCountry
		{
			get { return MBran.Models.BusinessAddress.GetBusinessAddressCountry(this); }
		}

		///<summary>
		/// State
		///</summary>
		[ImplementPropertyType("businessAddressState")]
		public string BusinessAddressState
		{
			get { return MBran.Models.BusinessAddress.GetBusinessAddressState(this); }
		}

		///<summary>
		/// Zip
		///</summary>
		[ImplementPropertyType("businessAddressZip")]
		public string BusinessAddressZip
		{
			get { return MBran.Models.BusinessAddress.GetBusinessAddressZip(this); }
		}

		///<summary>
		/// Timings
		///</summary>
		[ImplementPropertyType("businessTimings")]
		public IEnumerable<IPublishedContent> BusinessTimings
		{
			get { return MBran.Models.BusinessTimingsNested.GetBusinessTimings(this); }
		}

		///<summary>
		/// Favicon
		///</summary>
		[ImplementPropertyType("favicon")]
		public IPublishedContent Favicon
		{
			get { return MBran.Models.ImageFavicon.GetFavicon(this); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo
		{
			get { return MBran.Models.ImageLogo.GetLogo(this); }
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("navigationListFooter")]
		public IEnumerable<IPublishedContent> NavigationListFooter
		{
			get { return MBran.Models.NavigationFooter.GetNavigationListFooter(this); }
		}

		///<summary>
		/// Footer Utility
		///</summary>
		[ImplementPropertyType("navigationListFooterUtility")]
		public IEnumerable<IPublishedContent> NavigationListFooterUtility
		{
			get { return MBran.Models.NavigationFooterUtility.GetNavigationListFooterUtility(this); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("navigationListHeader")]
		public IEnumerable<IPublishedContent> NavigationListHeader
		{
			get { return MBran.Models.NavigationHeader.GetNavigationListHeader(this); }
		}

		///<summary>
		/// Header Utility
		///</summary>
		[ImplementPropertyType("navigationListHeaderUtility")]
		public IEnumerable<IPublishedContent> NavigationListHeaderUtility
		{
			get { return MBran.Models.NavigationHeaderUtility.GetNavigationListHeaderUtility(this); }
		}
	}
}
