//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Models
{
	/// <summary>Text And Image Left</summary>
	[PublishedContentModel("textAndImageLeft")]
	public partial class TextAndImageLeft : PublishedContentModel, IContentHeader, IContentImageFile
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "textAndImageLeft";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TextAndImageLeft(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TextAndImageLeft, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Summary
		///</summary>
		[ImplementPropertyType("contentSummary")]
		public string ContentSummary
		{
			get { return MBran.Models.ContentHeader.GetContentSummary(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("contentTitle")]
		public string ContentTitle
		{
			get { return MBran.Models.ContentHeader.GetContentTitle(this); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("contentImage")]
		public IPublishedContent ContentImage
		{
			get { return MBran.Models.ContentImageFile.GetContentImage(this); }
		}
	}
}
