//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Umbraco
{
	// Mixin content Type 1062 with alias "sitemapSettings"
	/// <summary>_SitemapSettings</summary>
	public partial interface ISitemapSettings : IPublishedContent
	{
		/// <summary>Hide in sitemap</summary>
		bool UmbracoNaviHide { get; }
	}

	/// <summary>_SitemapSettings</summary>
	[PublishedContentModel("sitemapSettings")]
	public partial class SitemapSettings : PublishedContentModel, ISitemapSettings
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sitemapSettings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SitemapSettings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SitemapSettings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hide in sitemap
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Hide in sitemap</summary>
		public static bool GetUmbracoNaviHide(ISitemapSettings that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }
	}
}
