//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Models
{
	// Mixin content Type 1086 with alias "businessTimingsNested"
	/// <summary>_BusinessTimings (Nested)</summary>
	public partial interface IBusinessTimingsNested : IPublishedContent
	{
		/// <summary>Timings</summary>
		IEnumerable<IPublishedContent> BusinessTimings { get; }
	}

	/// <summary>_BusinessTimings (Nested)</summary>
	[PublishedContentModel("businessTimingsNested")]
	public partial class BusinessTimingsNested : PublishedContentModel, IBusinessTimingsNested
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "businessTimingsNested";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BusinessTimingsNested(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BusinessTimingsNested, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Timings
		///</summary>
		[ImplementPropertyType("businessTimings")]
		public IEnumerable<IPublishedContent> BusinessTimings
		{
			get { return GetBusinessTimings(this); }
		}

		/// <summary>Static getter for Timings</summary>
		public static IEnumerable<IPublishedContent> GetBusinessTimings(IBusinessTimingsNested that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("businessTimings"); }
	}
}
