//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Models
{
	// Mixin content Type 1110 with alias "navigationHeaderUtility"
	/// <summary>_Navigation Header Utility</summary>
	public partial interface INavigationHeaderUtility : IPublishedContent
	{
		/// <summary>Header Utility</summary>
		IEnumerable<IPublishedContent> NavigationListHeaderUtility { get; }
	}

	/// <summary>_Navigation Header Utility</summary>
	[PublishedContentModel("navigationHeaderUtility")]
	public partial class NavigationHeaderUtility : PublishedContentModel, INavigationHeaderUtility
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigationHeaderUtility";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationHeaderUtility(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationHeaderUtility, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header Utility
		///</summary>
		[ImplementPropertyType("navigationListHeaderUtility")]
		public IEnumerable<IPublishedContent> NavigationListHeaderUtility
		{
			get { return GetNavigationListHeaderUtility(this); }
		}

		/// <summary>Static getter for Header Utility</summary>
		public static IEnumerable<IPublishedContent> GetNavigationListHeaderUtility(INavigationHeaderUtility that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("navigationListHeaderUtility"); }
	}
}
